### ISSUE TITLE
EC not usable

### ISSUE THREAD

**Issue by UltraBlackLinux** [WeiiswurstDev/EasyConomy#1] opened 2020-07-26 17:12 UTC
Hi,
EC seems to to be broken: The chestcommands plugin does not recognize it as eco plugin.
Thanks!
(Endlich mal ein Plugin mit demselben system wie EssX)

**Comment by ArvedEh** [comment] 2020-07-26 19:52
Vault has to be installed on the server.

For quicker help, please join [the support discord](
https://discord.gg/YDkQbE7 <https://discord.gg/YDkQbE7)as>) as I will see
your questions sooner there.

Also make sure that ChestCommands uses Vault! If the issue persists, please
ask on the support discord.

I hope I could help you

**Comment by UltraBlackLinux** [comment] 2020-07-26 21:09
Chestcommands uses vault. I used essentials' eco sys before and It worked perfectly.

**Comment by ArvedEh** [comment] 2020-07-26 21:17
So what
- version of EasyConomy
- version of Vault
- version of MC
do you use?

**Comment by UltraBlackLinux** [comment] 2020-07-27 19:21
mc 1.12.2, newest Vault, newest EC

**Comment by ArvedEh** [comment] 2020-07-27 20:04
Okay, I will look into that.

**Comment by ArvedEh** [comment] 2020-07-28 10:32
I tried it today with this setup:

- Paper 1.12.2 b1618
- ChestCommands 3.3.1
- EasyConomy  1.1
- Vault 1.7.3

I changed no configuration files.
**Everything worked as intended.**

I have to conclude that the issue you have is special to your setup.
If you changed any configuration files in any of these plugins, uploading those to a paste site like https://hasteb.in/ could maybe help me in finding the bug.
Another very useful thing would be the part of the logs when the plugins interact with each other (e.g. you click on a GUI Item that gives you money) because EasyConomy gives quite detailed output on that.

**Comment by UltraBlackLinux** [comment] 2020-07-28 14:09
Im not using paper, Im using magma (sry I forgot to tell you)
![Screenshot_20200728_160611](https://user-images.githubusercontent.com/62404294/88676373-4499a280-d0ec-11ea-95d7-7dc3b7c78d1d.png)

**Comment by ArvedEh** [comment] 2020-07-28 16:57
It seems like you did not read my message.
>  If you changed any configuration files in any of these plugins, uploading those to a paste site like https://hasteb.in/ could maybe help me in finding the bug.
> Another very useful thing would be the part of the logs when the plugins interact with each other (e.g. you click on a GUI Item that gives you money) because EasyConomy gives quite detailed output on that.

_Ich hab keine Lust dir jede Info aus der Nase rauszuziehen deshalb stelle ich doch die ganzen Fragen ...._

**Comment by UltraBlackLinux** [comment] 2020-07-28 21:03
This wasnt my full answer yet, just a part of the Info. I didnt have time to obtain the logs today.

**Comment by UltraBlackLinux** [comment] 2020-07-29 09:28
I now read through the logs and there are NONE. Not even a java error. just nothing.

**Comment by ArvedEh** [comment] 2020-07-29 12:58
We are now resolving it on discord :)

**Closed as completed by ArvedEh** 2020-07-29 12:58 UTC
